obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.30
inflation_radius: 0.75 # 0.55

observation_sources: laser_scan_sensor # point_cloud_sensor

laser_scan_sensor: {sensor_frame: base_range_sensor_link, data_type: LaserScan, topic: /hsrb/base_scan, marking: true, clearing: true}

# TODO: generate pointcloud2 data from depth image first
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
